import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import records from '../data/runway_data'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import CloseSharpIcon from '@mui/icons-material/CloseSharp';
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';


export default function Home() {
  const [bodyType, setBodyType] = useState();

  useEffect(() => {
    document.title = "Review by Users";
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={styles.main2}>
      <div className={styles.heading} id="heading">
        <div>
          <img src="/logo.png" width={80} height={80}/>
          <h2>PeriWinkie</h2>
          <Link href="/"><h2> Homepage <Image src="/cursor.png" width={15} height={20}/></h2></Link>
        </div>
          <h1>REVIEW</h1>
      </div>
      
      <div className={styles.review_cont} id="review_cont">
        <form>
          <h3>BODY TYPE</h3>
          <select onChange={(e) => {setBodyType(e.target.value)}}>
            <option value="all">all</option> 
            <option value="hourglass">hourglass</option> 
            <option value="athletic">athletic</option> 
            <option value="full bust">full bust</option> 
            <option value="petite">petite</option> 
            <option value="straight & narrow">straight & narrow</option> 
            <option value="pear">pear</option> 
            <option value="apple">apple</option> 
          </select>
        </form>

          <div className={styles.cont} id="cont"> 
            {
              records.map((rec, index) => {
                if(rec["body type"] == bodyType) {
                return(
                  <div className={styles.cont1}>
                    <div className={styles.box1}>
                      <div className={styles.line1}>
                        <div className={styles.box2}>  
                          <FavoriteBorderIcon sx={{ fontSize: 20}} className={styles.like}/> 
                        </div>
                        <div className={styles.box2}>  
                          <CloseSharpIcon/> 
                        </div>
                      </div>
                    
                    {rec["body type"] == bodyType ? 
                    <div key={index} className={styles.cont2}>
                      <div className={styles.cont3}>
                   
                          <div> <span>Rating </span> <span>{rec.rating}</span></div>
                          <div className={styles.bodyDesc}>
                            <div> <span>Body Type</span> {rec["body type"]}</div>
                            <div> <span>Height</span> {!rec.height ? " -": rec.height }</div>
                            <div> <span>Weight</span>{!rec.weight ? " -" : rec.weight }</div>
                          </div>
                       
                      </div>
                      <div><span>Review</span> <hr/> {rec.review_text}</div>
                    </div> : null
                    }
                    </div>
                  </div>
                )
              } else if (bodyType == "all") {
                return(
                  <div className={styles.cont1}>
                     <div className={styles.box1}>
                      <div className={styles.line1}>
                        <div className={styles.box2}>  
                          <FavoriteBorderIcon sx={{ fontSize: 20}}/> 
                        </div>
                        <div className={styles.box2}>  
                          <CloseSharpIcon/> 
                        </div>
                      </div>
                    <div key={index} className={styles.cont2}>
                      <div className={styles.cont3}>
                        <div> <span>Rating </span> <span>{rec.rating}</span></div>
                          <div className={styles.bodyDesc}>
                            <div> <span>Body Type</span> {rec["body type"]}</div>
                            <div> <span>Height</span> {!rec.height ? " -": rec.height }</div>
                            <div> <span>Weight</span>{!rec.weight ? " -" : rec.weight }</div>
                          </div>
                      </div>
                      <div><span>Review</span> <hr/> {rec.review_text}</div>
                    </div> 
                    </div>
                  </div>
                )
              } 
              }
            )} 
          </div>   
        </div>     
      </main>
    </>
  )
}
